- name: Add SSH public key to GitHub account
  ansible.builtin.uri:
    url: https://api.github.com/user/keys
    validate_certs: false
    method: POST
    body:
      title: "{{ key_title }}"
      key: "{{ key_content.stdout }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      # FIXME: use ansible-vault to encrypt GH_PAT
      Authorization: "token {{ lookup('env', 'GH_PAT') }}"
    status_code: 200, 201
  register: task_log
