networks:
  caddy:
services:
  remark:
    build:
      context: ./remark42/remark42
      args:
        SKIP_FRONTEND_TEST: "true"
        SKIP_BACKEND_TEST: "true"
    image: atlasview/remark42:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    expose:
      - "8080"
    environment:
      - REMARK_URL=https://localhost/remark
      - SECRET=12345
      - DEBUG=true
      - AUTH_ANON=true
      - SITE=atlasview
      - ANON_VOTE=true
      - VOTES_IP=true
    volumes:
      - ./var:/srv/var
    networks:
      - caddy
  shiny:
    build: ./shiny-app
    image: atlasview/shiny:latest
    restart: unless-stopped
    environment:
      - ATLASVIEW_DATA_PATH=/etc/shiny-app/data
    volumes:
      - /Users/tamuri/Documents/2023/disease_atlas/atlasview-data:/etc/shiny-app/data
    expose:
      - "3838"
    networks:
      - caddy
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddyserver/Caddyfile:/etc/caddy/Caddyfile 
      - ./caddyserver/certs:/etc/caddy/certs
    depends_on:
      - shiny
      - remark
    networks:
      - caddy

