# Run the application using:
# REMARK_SECRET=<remark secret key> SITE_ADDRESS=<DNS name of host> docker compose up -d

networks:
  caddy:

# There are three services running: the Remark commenting engine, R Shiny server and Caddy server tying them together
# All services assume the AtlasView data directory lives at `../atlasview-data/`. Change if this is not the case.
services:
  remark:
    # We're building Remark from out own copy of the source code, 
    # rather than the available pre-built image. This is because we patch the 
    # source code to remove the ability to logout.
    build:
      context: ./remark42/remark42
      args:
        # We don't run tests to reduce build time
        SKIP_FRONTEND_TEST: "true"
        SKIP_BACKEND_TEST: "true"
    image: atlasview/remark42:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    expose:
      - "8080"
    environment:
      - REMARK_URL=https://${ATLASVIEW_SITE_ADDRESS}/remark
      - SECRET=${REMARK42_SECRET}
      - DEBUG=false
      - AUTH_ANON=true
      - SITE=atlasview
      - ANON_VOTE=true
      - VOTES_IP=true
      - ALLOWED_HOSTS=${ATLASVIEW_SITE_ADDRESS}
      - ADMIN_PASSWD=${REMARK42_ADMIN_PASSWD}
    volumes:
      - ../atlasview-data/remark:/srv/var
    networks:
      - caddy
  shiny:
    build: ./shiny-app
    image: atlasview/shiny:latest
    restart: unless-stopped
    environment:
      - ATLASVIEW_DATA_PATH=/etc/shiny-app/data
      - REMARK_SECRET=${REMARK42_SECRET}
    volumes:
      - ../atlasview-data:/etc/shiny-app/data
    expose:
      - "3838"
    networks:
      - caddy
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=${ATLASVIEW_SITE_ADDRESS}
    volumes:
      - ./caddyserver/Caddyfile:/etc/caddy/Caddyfile
      - ../atlasview-data/caddy/data:/data
      - ../atlasview-data/caddy/config:/config
    depends_on:
      - shiny
      - remark
    networks:
      - caddy

