networks:
  caddy:
services:
  remark:
    build:
      context: ./remark42/remark42
      args:
        SKIP_FRONTEND_TEST: "true"
        SKIP_BACKEND_TEST: "true"
    image: atlasview/remark42:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    expose:
      - "8080"
    environment:
      - REMARK_URL=https://localhost/remark
      - SECRET=${REMARK_SECRET}
      - DEBUG=false
      - AUTH_ANON=true
      - SITE=atlasview
      - ANON_VOTE=true
      - VOTES_IP=true
    volumes:
      - ../atlasview-data/remark:/srv/var
    networks:
      - caddy
  shiny:
    build: ./shiny-app
    image: atlasview/shiny:latest
    restart: unless-stopped
    environment:
      - ATLASVIEW_DATA_PATH=/etc/shiny-app/data
      - REMARK_SECRET=${REMARK_SECRET}
    volumes:
      - ../atlasview-data:/etc/shiny-app/data
    expose:
      - "3838"
    networks:
      - caddy
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    volumes:
      - ./caddyserver:/etc/caddy
    depends_on:
      - shiny
      - remark
    networks:
      - caddy

