- name: Create atlasview placeholder directory
  ansible.builtin.file:
    path: "{{ remote.atlasview_main }}"
    state: directory
    mode: "0755"

- name: Copy local atlasview-data directory
  ansible.builtin.copy:
    src: "{{ local.atlasview_data }}"
    dest: "{{ atlasview_root }}"
    mode: "0755"

- name: Copy local .env file
  ansible.builtin.copy:
    src: "{{ local.atlasview_env }}"
    dest: "{{ remote.atlasview_env }}"
    mode: "0644"

- name: Create atlasview-backups directory
  ansible.builtin.file:
    path: "{{ remote.atlasview_backups }}/comments"
    state: directory
    mode: "0755"
