- name: Setup GHA runner
  ansible.builtin.include_role:
    name: monolithprojects.github_actions_runner
  vars:
    # FIXME: use `ansible-vault` to encrypt this variable instead
    access_token: "{{ lookup('env', 'GH_PAT') }}"
    runner_dir: /opt/actions-runner/{{ github_account }}/{{ github_repo }}
  tags:
    - uninstall  # To uninstall the runner with ansible-playbook playbook.yml --tags uninstall
