- name: Clone atlasview repo
  ansible.builtin.git:
    repo: "git@github.com:{{ atlasview_repo }}.git"
    dest: "{{ remote.atlasview_main }}"
    version: "{{ atlasview_branch }}"
    force: true

- name: Copy local atlasview-data files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ remote.atlasview_data }}/"
    mode: "0644"
  ## Only copy over the CSV files from the local machine
  ## `atlasview-data` also contains config files for caddy and remark,
  ## which should not be copied over!
  with_fileglob: "{{ local.atlasview_data }}/*.csv"

- name: Set up Remark42 engine
  ansible.builtin.script:
    cmd: "{{ setup_remark42 }}"
    chdir: "{{ remote.atlasview_main }}"

- name: Create atlasview-backups directory
  ansible.builtin.file:
    path: "{{ remote.atlasview_backups }}/comments"
    state: directory
    mode: "0755"

- name: Make sure rclone and zip are installed
  ansible.builtin.apt:
    pkg:
      - rclone
      - zip
    state: latest
    update_cache: true

- name: Set up rclone syncing
  ansible.builtin.script:
    cmd: "{{ setup_rclone }}"
    chdir: "{{ atlasview_root }}"

- name: Set up backups cron job
  ansible.builtin.include_tasks: do-backup-cron.yml

- name: Set up backup rotation
  ansible.builtin.include_tasks: rotate-backups.yml
