name: Docker Build CD

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Deploy
      run: ./deployment/deploy.sh
      working-directory: /home/ubuntu/atlasview
