name: Docker Build CD

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        packages: |
          any::usethis
          any::gert
          any::desc

    - name: Bump shiny-app package version
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        Rscript ./deployment/update-shiny-app-version.R

    - name: Deploy
      run: ./deployment/deploy.sh

