name: Docker Build CD

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Deploy
      run: ./deployment/deploy.sh
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
